services:

  postgresql:
    image: ${POSTGRESQL_IMAGE_NAME}:${POSTGRESQL_IMAGE_VERSION}
    shm_size: ${POSTGRESQL_SHARED_BUFFERS_SIZE}
    ports:
      - "${POSTGRESQL_EXPOSED_PORT}:${POSTGRESQL_INTERNAL_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_USER_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE_NAME}
    healthcheck:
      test: "psql --dbname \"host=localhost port=${POSTGRESQL_INTERNAL_PORT} dbname=${POSTGRESQL_DATABASE_NAME} user=${POSTGRESQL_USER_NAME} password=${POSTGRESQL_USER_PASSWORD}\""
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./configuration:/bitnami/postgresql/conf
    deploy:
      resources:
        limits:
          cpus: '${POSTGRESQL_CPU_COUNT}'
          memory: ${POSTGRESQL_TOTAL_MEMORY_SIZE}